[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
solana-sdk = "2"
solana-client = "2"
solana-account-decoder = "2"
